""" Distinct Powers

Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
    <combinations>
If they are then placed in numerical order, with any repeats removed, we get the
  following sequence of 15 distinct terms:
    4,8,9,16,25,27,32,64,81,125,243,256,625,1024,3125.
How many distinct terms are there in the sequence generated by a^b for 2 <= a <=
  100 and 2 <= b <= 100?
https://projecteuler.net/problem=29
"""

__author__ = "Liam Anthian"

# --- Conditions of the problem ---
A_RANGE = range(2,101)
B_RANGE = range(2,101)


# --- Calculation & Output ---
def main():
    print(len(set([a**b for b in B_RANGE for a in A_RANGE]))) # 9,183
    return
